// <auto-generated>
// Rust port of OpRoleMemberLogic.core.cs.
//
// Partial-class equivalent: the `op_role_member` table already generates the
// `OpRoleMemberLogic` type (in the `op_role_member_logic` module). This module
// adds authorization behaviour to that same type via an inherent `impl` block
// referenced by full path (an inherent impl may live in any module of the
// defining crate).
//
// Tracks the authenticated principal for the current execution context and
// answers operation/role authorization questions, caching results. .NET used
// AsyncLocal; the synchronous Rust stack uses a thread-local with an OS-user
// fallback for non-web contexts (scheduler, scripts, tests).
// </auto-generated>

use std::cell::RefCell;
use std::collections::HashMap;
use std::sync::{Mutex, OnceLock};

use common::{BaseObject, Logger};
use persist::{DBPersist, PersistError};
use serde_json::Value;

thread_local! {
    static CURRENT_USER: RefCell<Option<String>> = const { RefCell::new(None) };
}

fn auth_cache() -> &'static Mutex<HashMap<String, bool>> {
    static CACHE: OnceLock<Mutex<HashMap<String, bool>>> = OnceLock::new();
    CACHE.get_or_init(|| Mutex::new(HashMap::new()))
}

impl crate::op_role_member_logic::OpRoleMemberLogic {
    pub fn set_current_user(username: Option<&str>) {
        Logger::debug(format!("Setting current user to {:?}", username));
        CURRENT_USER.with(|u| *u.borrow_mut() = username.map(|s| s.to_string()));
    }

    pub fn current_user() -> String {
        CURRENT_USER
            .with(|u| u.borrow().clone())
            .unwrap_or_else(auth_os_user)
    }

    pub fn authorized(object_name: &str, method_name: &str) -> Result<bool, PersistError> {
        let email = Self::current_user();
        Logger::debug(format!(
            "Checking authorization for {} on {}.{}",
            email, object_name, method_name
        ));

        let key = format!("{}:{}:{}", email, object_name, method_name);

        if let Some(cached) = auth_cache().lock().unwrap().get(&key) {
            return Ok(*cached);
        }

        let sql = r#"select 1 from
core.operation op
inner join core.op_role_map orm on
    orm.op_id=op.id 
	and orm.is_active=1
inner join core.op_role r on
    r.id=orm.op_role_id
	and r.is_active=1
inner join core.op_role_member m on
    m.op_role_id=r.id
	and m.is_active=1
inner join core."principal" p on
    p.id=m.principal_id
	and p.is_active=1 
	and p.principal_status_id=(select id from core.principal_status where name='Enabled')
where op.objectname = '^(objectname)' 
    and op.methodname = '^(methodname)'
    and (p.email = '^(email)' OR p.username = '^(username)')"#;

        let mut filter = BaseObject::new();
        filter.set("objectname", Value::String(object_name.to_string()));
        filter.set("methodname", Value::String(method_name.to_string()));
        filter.set("email", Value::String(email.clone()));
        filter.set("username", Value::String(email.clone()));

        let rows = DBPersist::select_template(sql, &filter, "default")?;
        let result = !rows.is_empty();

        auth_cache().lock().unwrap().insert(key, result);
        Ok(result)
    }

    pub fn clear_auth_cache() {
        auth_cache().lock().unwrap().clear();
    }
}

fn auth_os_user() -> String {
    std::env::var("USER")
        .or_else(|_| std::env::var("USERNAME"))
        .unwrap_or_else(|_| "unknown".to_string())
}
